### ISSUE TITLE
Site just loads "Page not found"

### ISSUE THREAD

**Issue by realdeadbeef** [Sped0n/bridget#378]
### Step to reproduce

1. `hugo new site sitename`
2. `cd sitename`
3. `git init`
4. `git submodule add https://github.com/Sped0n/bridget themes/bridget`
5. Remove `hugo.toml` from project root
6. Copy config folder from exampleSite to project root
7. Set theme config as follows:

```toml
# theme as module
[module]
replacements = "github.com/Sped0n/bridget/v2 -> themes/bridget" # deploy with local dir  WARN: delete this line if you want to deploy with git
[[module.imports]]
path = "github.com/Sped0n/bridget/v2" # deploy with git (recommended)  WARN: you should also set `bundled` to true in params.toml !!!
```

8. `mkdir ./content/Info`
9. Write the default index.md headings to index.md in the Info folder.
10. `hugo serve`

### Expected behaviour

Build a site, idk what else to say?

### Actual Behaviour

![image](https://github.com/user-attachments/assets/4c728191-ade9-4843-8fd1-636a25458334)

### Logs

```
Watching for changes in /home/deadbeef/Documents/tomtakesphotos.com/{archetypes,assets,content,data,i18n,layouts,static}
Watching for config changes in /home/deadbeef/Documents/tomtakesphotos.com/hugo.toml, /home/deadbeef/Documents/tomtakesphotos.com/config/_default
Start building sites … 
hugo v0.132.2-3fd26c70dff5934ec1802b9563530130ed1bca75+extended linux/amd64 BuildDate=2024-08-14T16:17:21Z VendorInfo=gohugoio

WARN  found no layout file for "html" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "json" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  2  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Cleaned          |  0  

Built in 5 ms
```

### Hugo version

v0.132.2 (extended)

### Bridget version

v2.0.3

### OS version

Linux Mint and Debian

### Verify steps

- [ ] Pull request is welcome. Check this if you want to start a pull request
- [X] I have searched on [Issue Tracker](https://github.com/Sped0n/bridget/issues), No duplicate or related open issue has been found
- [X] Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
